const ENV = {
    API_URL: 'http://localhost:5001/',
    API_URL_UPLOADS_ACTORS: 'http://localhost:5001/uploads/actors/',
    API_URL_UPLOADS_MOVIES: 'http://localhost:5001/uploads/movies/',
    API_URL_UPLOADS_MAIN_SLIDER: 'http://localhost:5001/uploads/slider/main/',
    API_ACTORS: 'api/actors',
    API_MOVIE_ACTORS: 'api/movie_actors',
    API_ADD_ACTOR: 'api/api/add-actor',
    API_MOVIES_COUNT: '/api/movies-count',
    API_MOVIE: 'api/movie/',
    API_MOVIE_PROPERTIES: 'api/properties/',
    API_MOVIES: 'api/movies',
    API_LAST_MOVIES: 'api/last-movies',
    API_TOP_MOVIES: 'api/top-movies',
    API_ADD_MOVIE: 'api/add-movie',
    API_SEARCH_MOVIE: 'api/search-movie',
    API_SET_MOVIE_RATING: 'api/set-rating',
    API_MOVIE_FAVORITE: 'api/add-favorite',
    API_MOVIES_FAVORITES: 'api/favorites',

    API_USERS: '/api/users',
    API_CREATE_USER: 'api/create-user/',
    API_AUTH: 'api/auth/',
    API_LOGOUT: 'api/logout/',
    API_REFRESH_TOKEN: 'api/refresh-token/',
    API_PROFILE: 'api/profile/',

    API_SLIDES: '/api/get-slides',
    API_ADD_SLIDE: '/api/add-slide',
    API_GET_SLIDE: '/api/get-slide',
    API_DELETE_SLIDE: '/api/delete-slide',
    API_UPDATE_SLIDE: '/api/update-slide',
    CLIENT_URL: 'http://localhost:3000/',
    MOVIES_URL: 'http://localhost:3000/movies/',
    MOVIES: '/movies/',
    EDIT_SLIDER: '/admin/edit-slider/',
    ADD_MOVIE: '/admin/add-movie/',
    ADD_ACTOR: '/admin/add-actor/',
    ADMIN:'/admin/',
}

export default ENV;